### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('localhost://') does not match the recipient window's origin ('http://localhost:3050').

### ISSUE THREAD

**Issue by Falieson** [mondora/asteroid-oauth-mixin#9]
**My Setup:**
React/Express: Port 3000
Meteor: Port 3050

**STEPS TO REPRODUCE**

1. When I execute DDP.loginWith('google')
2. A blank popup appears (my browser is already signed into google)
3. The console of the new window reports ERRORS

**ERRORS**
```
end_of_popup_response.js:18 Uncaught DOMException: Blocked a frame with origin "http://localhost:3050" from accessing a cross-origin frame.
    at http://localhost:3050/packages/oauth/end_of_popup_response.js:18:39
    at http://localhost:3050/packages/oauth/end_of_popup_response.js:37:3
(anonymous) @ end_of_popup_response.js:18
(anonymous) @ end_of_popup_response.js:37
2827:3000/static/js/bundle.js:2456 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('localhost://') does not match the recipient window's origin ('http://localhost:3050').
```

**ISSUE**
Why am I getting `The target origin provided 'localhost://'` instead of localhost:3000 or localhost:3050? (which ever the right one is)

**Changes I've made to the Example:**
```
const DDP_CONFIG = {
  endpoint: process.env.DDP_ENDPOINT,
  platform: 'browser'
}
const DDP: IddpClient = new DDPclient(DDP_CONFIG || {
  endpoint: 'ws://localhost:3050/websocket'
})

DDP.loginServiceConfiguration = {}
DDP.ddp.on('added', ({collection, id, fields}: { collection: string; fields: {service: string}, id: string }) => {
  if (collection === 'meteor_accounts_loginServiceConfiguration') {
    DDP.loginServiceConfiguration = {
      ...DDP.loginServiceConfiguration,
      [fields.service]: { // NOTE! fields.service INSTEAD of id b/c this matches up with 'providerName' below
        _id: id,
        ...fields
      }
    }
  }
})
DDP.getServiceConfig = function(providerName: string) {
  return this.loginServiceConfiguration[providerName]
}
```

@AayushShrestha @fmondora can you help me with this?

**Comment by AayushShrestha** [comment]
@Falieson 
1. You have to register the redirect URI in the APIs console. Go to [Google Cloud Console](console.cloud.google.com) , look under "API Access". You should see your client ID and secret there and a list of redirect URIs. Make sure there is localhost:3050 in that list.

2. You might also want to set Access-Control-Allow-Origin on your meteor server to allow requests from localhost:3000. You might want to use [this](https://github.com/mondora/mondora-asteroid) package to do that.

**Comment by Falieson** [comment]
@AayushShrestha Thank you! That did it! I owe you a :beer:

**Comment by Falieson** [comment]
@AayushShrestha I can't get it working on my production server and can't figure out why! I've been trying for a couple weeks. Do you know why theres only a meteor server console error for redirect_uri_mismatch in my prodcase while locally I'm getting an error rendered in browser? The browser rendered error states what is being submitted for verification

I'm trying to figure out what uri the server is trying to match but the console error doesn't say.
I've tried running my server in development (its not a real production server) mode, but I don't get the browser rendered error - maybe b/c I'm using ports 80/443 on the express server? the meteor server is just 3050/3443
